# snakemake_environment.yml
name: snakemake_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal >=7.0 # Snakemake 실행에 필요한 최소 패키지
  - python >=3.8
  - pyyaml # Snakemake가 config.yml을 읽기 위해 필요
  # (선택) DAG 시각화를 위한 graphviz 추가 가능
  # - graphviz